.PHONY: 01-basics 02-asynckernel 03-asyncmemcopy 04-eventsync
all: 01-basics 02-asynckernel 03-asyncmemcopy 04-eventsync

01-basics:
	CC -xhip 01-basics.cpp -o 01-basics

02-asynckernel:
	CC -xhip 02-asynckernel.cpp -o 02-asynckernel

03-asyncmemcopy:
	CC -xhip 03-asyncmemcopy.cpp -o 03-asyncmemcopy

04-eventsync:
	CC -xhip 04-eventsync.cpp -o 04-eventsync
