name: Deploy HTML and PDF slides to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - "master"
    paths:
      - "*/docs/**"
      - ".github/workflows/pages.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pages-pdf:
    uses: ./.github/workflows/pages.yml
    with:
      include_pdf: true
